language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.zinc

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  # Workaround to avoid 'The log length has exceeded the limit of 4 MB' limitation
  # when downloading all dependencies and plugins (after long time without builds)
  # --quiet option limits logs to errors only
  - mvn compile -Ptravis --quiet --fail-never --update-snapshots --settings .travis.settings.xml -e

script:
  - mvn verify site --update-snapshots --settings .travis.settings.xml -e

jdk: openjdk8
